#!/bin/bash
arduino-cli compile -b arduino:mbed_portenta:envie_m7 --library "../../POSIXStorage" --library  "/home/c.dragomir/ArduinoWorkspace/arduino_UnifiedStorage"
arduino-cli upload -b arduino:mbed_portenta:envie_m7