#!/bin/bash
arduino-cli compile -b arduino:renesas_portenta:portenta_c33  --library "../../Arduino_POSIXStorage" --library  "/home/c.dragomir/ArduinoWorkspace/Arduino_UnifiedStorage"
arduino-cli upload -b arduino:renesas_portenta:portenta_c33 