#!/bin/bash
arduino-cli compile -b arduino:mbed_portenta:envie_m7 --library "../../Arduino_POSIXStorage" --library  "/home/c.dragomir/ArduinoWorkspace/Arduino_UnifiedStorage"
arduino-cli upload -b arduino:mbed_portenta:envie_m7